language: go

go:
    - 1.5
    - 1.6

git:
    depth: 1

sudo: required

install:
    - go get -v -d

script:
    - make && make test

after_success:
    - echo $TRAVIS_GO_VERSION
    - if [ ! -z $TRAVIS_TAG ] && [ $TRAVIS_GO_VERSION == "1.6" ];
      then echo $UPX_CONFIG > $HOME/.upx.cfg && make upload;
      fi
